Askoro/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from decouple import config

urlpatterns = [
    path(config('ADMIN_URL'), admin.site.urls),
    path('signup/', user_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    path('', include('doubts.urls', namespace='doubts')),
    path('', include('social_django.urls', namespace='social')),

    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
        name='password_reset'
        ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'
        ),
    path(
        'password_reset_confirm/<uidb64>/<token>',
        auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
        ),
    path(
        'password_reset_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
        ),

    path(
        'email_verification_confirm/<uidb64>/<token>',
        user_views.email_verification_confirm,
        name='email_verification_confirm'
        ),
    path('email_verification_done/', user_views.email_verification_done, name='email_verification_done'),
    path('privacy_policy/', user_views.privacy_policy, name='privacy_policy'),

]

doubts/urls.py
from django.urls import path
from .views import (
    UserIndexView,
    IndexView,
    QuestionDetailsView,
    QuestionCreateView,
    QuestionEditView,
    AnswerCreateView,
    AnswerEditView,
    AnswerDeleteView,
    QuestionUpvoteView,
    AnswerUpvoteView,
)
app_name = 'polls'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:pk>/', QuestionDetailsView.as_view(), name='details'),
    path('user/<int:pk>/', UserIndexView.as_view(), name='user-index'),
    path('create/', QuestionCreateView.as_view(), name='create-question'),
    path('<int:pk>/edit/', QuestionEditView.as_view(), name='edit-question'),  # No delete functionality by choice
    path('<int:qid>/answer/', AnswerCreateView.as_view(), name='create-answer'),
    path('<int:qid>/edit-answer/<int:pk>', AnswerEditView.as_view(), name='edit-answer'),
    path('<int:qid>/delete-answer/<int:pk>', AnswerDeleteView.as_view(), name='delete-answer'),
    path('vote-ques/<int:pk>/<int:ud>', QuestionUpvoteView.as_view(), name='vote-question'),
    path('vote-ans/<int:pk>/<int:ud>', AnswerUpvoteView.as_view(), name='vote-answer'),

]

doubts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth import get_user_model


def get_sentinel_user():
    return get_user_model().objects.get_or_create(username='deleted')[0]


class Question(models.Model):
    SUBJECT_CHOICES = [
        ('M', 'Mathematics'),
        ('P', 'Physics'),
        ('C', 'Chemistry'),
        ('CS', 'Computer Science')
    ]
    asker = models.ForeignKey(get_user_model(), on_delete=models.SET(get_sentinel_user))
    title = models.CharField(max_length=100)
    text = models.TextField(null=True)
    subject = models.CharField(max_length=2, choices=SUBJECT_CHOICES, default='C')
    hardness_points = models.IntegerField(default=0)
    date_asked = models.DateTimeField('Date Asked', auto_now_add=True)
    no_of_answers = models.IntegerField(default=0)
    upvotes_total = models.ManyToManyField(User, related_name="upvotes")
    downvotes_total = models.ManyToManyField(User, related_name="downvotes")

    def hasUserAnswered(self, u):
        for answer in self.answer_set.all():
            if u == answer.author:
                return True
        return False

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('doubts:details', kwargs={'pk': self.pk})


class Answer(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.SET(get_sentinel_user))
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.TextField()
    date_answered = models.DateTimeField('Date Answered', auto_now_add=True)
    upvotes = models.IntegerField(default=0)
    updated_time = models.DateTimeField(auto_now=True)
    upvoters = models.ManyToManyField(User, related_name="upvoters")
    downvoters = models.ManyToManyField(User, related_name="downvoters")

    def get_absolute_url(self):
        return reverse('doubts:details', kwargs={'pk': self.question.id})

doubts/forms.py
from django import forms
from .models import Answer, Question


class QuestionCreationForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ['title', 'text', 'subject']


class QuestionUpdateForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'text', 'subject']


class AnswerCreationForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text']


class AnswerUpdateForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text']

doubts/views.py
from django.shortcuts import get_object_or_404
from .models import Question, Answer
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse
from .forms import AnswerUpdateForm, AnswerCreationForm, QuestionCreationForm, QuestionUpdateForm
from django.contrib.auth.models import User


class IndexView(generic.ListView):
    model = Question
    template_name = "doubts/index.html"
    context_object_name = "latest_question_list"
    ordering = ['-date_asked']
    paginate_by = 10


class UserIndexView(generic.DetailView):
    model = User
    template_name = "doubts/user_index.html"


class QuestionDetailsView(generic.DetailView):
    model = Question
    template_name = "doubts/details.html"


class QuestionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Question
    form_class = QuestionCreationForm

    def form_valid(self, form):
        form.instance.asker = self.request.user
        return super().form_valid(form)


class QuestionEditView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Question
    form_class = QuestionUpdateForm

    def form_valid(self, form):
        form.instance.asker = self.request.user
        return super().form_valid(form)

    def test_func(self):
        question = self.get_object()
        return self.request.user == question.asker


class AnswerCreateView(LoginRequiredMixin, UserPassesTestMixin, generic.CreateView):
    model = Answer
    form_class = AnswerCreationForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.question = Question.objects.get(id=self.kwargs['qid'])
        return super().form_valid(form)

    def test_func(self):
        question = Question.objects.get(id=self.kwargs['qid'])
        return not question.hasUserAnswered(self.request.user)


class AnswerEditView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Answer
    form_class = AnswerUpdateForm

    def get_initial(self):
        initial = super().get_initial()
        obj = self.get_object()
        initial['text'] = obj.text
        return initial

    def get_success_url(self):
        question = self.object.question
        return reverse('doubts:details', kwargs={'pk': question.id})

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.question = Question.objects.get(id=self.kwargs['qid'])
        return super().form_valid(form)

    def test_func(self):
        answer = self.get_object()
        return self.request.user == answer.author


class AnswerDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Answer

    def get_success_url(self):
        question = self.object.question
        return reverse('doubts:details', kwargs={'pk': question.id})

    def test_func(self):
        answer = self.get_object()
        return self.request.user == answer.author


class QuestionUpvoteView(LoginRequiredMixin, UserPassesTestMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        question = get_object_or_404(Question, pk=self.kwargs['pk'])
        url = question.get_absolute_url()
        user = self.request.user
        ud = self.kwargs['ud']
        userwasdown = user in question.downvotes_total.all()
        userwasup = user in question.upvotes_total.all()
        if ud == 1:
            if userwasup:
                question.upvotes_total.remove(user)
                question.hardness_points -= 1

            elif userwasdown:
                question.downvotes_total.remove(user)
                question.upvotes_total.add(user)
                question.hardness_points += 2
            else:
                question.upvotes_total.add(user)
                question.hardness_points += 1
        else:
            if userwasdown:
                question.downvotes_total.remove(user)
                question.hardness_points += 1

            elif userwasup:
                question.upvotes_total.remove(user)
                question.downvotes_total.add(user)
                question.hardness_points -= 2
            else:
                question.hardness_points -= 1
                question.downvotes_total.add(user)
        question.save()
        return url

    def test_func(self):
        question = get_object_or_404(Question, pk=self.kwargs['pk'])
        user = self.request.user
        return not user == question.asker


class AnswerUpvoteView(LoginRequiredMixin, UserPassesTestMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        answer = get_object_or_404(Answer, pk=self.kwargs['pk'])
        diff = 0  # diff stores the difference there will be in the total number of upvotes
        url = answer.get_absolute_url()
        user = self.request.user
        ud = self.kwargs['ud']
        userwasdown = user in answer.downvoters.all()
        userwasup = user in answer.upvoters.all()
        if ud == 1:
            if userwasup:
                answer.upvoters.remove(user)
                diff = -1
            elif userwasdown:
                answer.downvoters.remove(user)
                answer.upvoters.add(user)
                diff = +2
            else:
                answer.upvoters.add(user)
                diff = +1
        else:
            if userwasdown:
                answer.downvoters.remove(user)
                diff = +1

            elif userwasup:
                answer.upvoters.remove(user)
                answer.downvoters.add(user)
                diff = -2
            else:
                diff = -1
                answer.downvoters.add(user)
        answer.upvotes += diff
        answer.author.profile.karma_points += diff
        answer.author.save()
        answer.save()
        return url

    def test_func(self):
        answer = get_object_or_404(Answer, pk=self.kwargs['pk'])
        user = self.request.user
        return not user == answer.author

doubts/templates/doubts/answer_confirm_delete.html
{%extends "doubts/base.html"%}
{%block content%}
<div class="content-section pd-8 ">
    <form method="POST">
        {%csrf_token%}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                Are you sure you want to delete that answer?
            </legend>
        </fieldset>
        <div class="form-group"><button class="btn btn-outline-danger" type="submit">Delete</button>
            <a class="btn btn-outline-secondary" style="margin-left: 20px;" href="{% url 'doubts:details' object.question.id %}">Cancel</a>
        </div>

    </form>
</div>

{%endblock content %}

doubts/templates/doubts/answer_form.html
{%extends "doubts/base.html"%}
{% load crispy_forms_tags%}
{%block content%}
<div class="content-section pd-8 ">
    <form method="POST">
        {%csrf_token%}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                Answer
            </legend>
            {{form|crispy}}
        </fieldset>
        <div class="form-group" style="text-align: right;"><button class="btn btn-outline-success" type="submit">Publish</button></div>
    </form>
</div>

{%endblock content %}

doubts/templates/doubts/base.html
{%load static%}

<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'doubts/style.css' %}">
    <script src="https://kit.fontawesome.com/c566c23470.js" crossorigin="anonymous"></script>
     <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Roboto&display=swap" rel="stylesheet">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <link href="{% static 'doubts/style.css' %}" rel="stylesheet" type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Askoro</title>
  </head>
  <body>
    <div style="min-height: 100%;">
    <!--Navbar Starts-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
      <a class="navbar-brand" href="{%url 'doubts:index'%}"><h3 style="font-family:  'Chelsea Market', cursive;">Askoro</h3></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">

        </div>
      <div class="navbar-nav ">
        {%if user.is_authenticated%}
            <a class="btn btn-outline-info nav-link" href="{% url 'doubts:create-question' %}" style="margin-right:25px">Ask Question</a>
            <a class="nav-link" href="{%url 'doubts:user-index' user.id%}">{{user.username}}</a>
            <a class="nav-link " href="{%url 'logout'%}"><small class="text-muted"><i class="fas fa-sign-out-alt"></i> Logout</small></a>
          {%else%}
            <a class="nav-link" href="{%url 'signup'%}">Signup</a>
            <a class="nav-link" href="{%url 'login'%}"><i class="fas fa-sign-in-alt"></i> Login</a>
          {%endif%}
      </div>
      </div>
    </div>
    </nav>
        <!--Navbar Ends-->

    <main role="main" class="container">
        <div class="col-md8 md-8 mt-8" style="padding-top: 20px;padding-bottom: 20px;overflow: hidden;">
            {%if messeages%}
                {%for message in messages%}
                <div class="ml-8 alert alert-{{message.tags}}">
                    {{message}}
                  </div>
                {%endfor%}
            {%endif%}

            {%block content%}

            {%endblock%}
        </div>

    </main>
  </div>
    <footer class="page-footer font-small pt-4" style='width: 100%;
    height: 200px;
    margin-top: 30px;
    margin-bottom: 0px;
    z-index: 12;
    bottom:0'></footerclass>
      <div class="footer-copyright text-center py-3">
        Made by <a href="https://github.com/Arhaan">Arhaan Ahmad</a>
      </div>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

doubts/templates/doubts/details.html
{% extends "doubts/base.html" %}
{% block content %}
{% load static %}
{%load doubts_extras%}
<link rel="stylesheet" type="text/css" href="{% static 'doubts/style.css' %}">

<div id='main-box'>
<div>
<div class="voting-question float-left" style='padding-right: 10px'>
    {%if user|has_upvotedques:question%}
    <div class="button ques-upvoted" ><a style="color:  #f48024;" class= "btn btn-light" href = "{%url 'doubts:vote-question' question.id 1%}"><i class="fa fa-arrow-up" ></i></a></div>
    {%else%}
    <div class="button" ><a style = "color:  #131010;" class= "btn btn-light"href = "{%url 'doubts:vote-question' question.id 1%}"><i class="fa fa-arrow-up" ></i></a></div>
    {%endif%}
    <div class="votes" style="padding-left: 15px;">{{question.hardness_points}}</div>
    {%if user|has_downvotedques:question%}
    <div class="button ques-downvoted"><a style = "color:  #f48024;" class= "btn btn-light"href= "{%url 'doubts:vote-question' question.id 0%}"><i class="fa fa-arrow-down"></i></a></div>
    {%else%}
    <div class="button"><a style = "color:  #131010;" class= "btn btn-light"href= "{%url 'doubts:vote-question' question.id 0%}"><i class="fa fa-arrow-down"></i></a></div>
    {%endif%}
</div>
<div id='ques-title'>
    <h2>{{question}}</h2>
</div>
<div id="details">
    <p>{{question.text|linebreaks|urlizetrunc:50}}</p>
    <small class='text-muted'>Asked By : <a class="profile-link" href={%url 'doubts:user-index' question.asker.id %}>{{question.asker}}</a></small>
    {%if question.asker == user%}
        <a class="float-right btn btn-outline-secondary btn-sm" href="{%url 'doubts:edit-question' question.pk%}">Edit</a>
    {%endif%}
</div>
</div>
<div id="answers" style="padding-top: 25px;padding-right: 10px;padding-bottom: 5px;">
<div id="answer-headers" style="padding-bottom: 10px; overflow: hidden;">
    <h2 class="float-left">{{question.answer_set.count}} Answer{{question.answer_set.count|pluralize}}</h2>
    {%if not user|has_answered:question%}
    <div class="float-right">
        <a class="btn btn-outline-secondary btn-sm" href="{%url 'doubts:create-answer' question.pk%}">Answer</a>
    </div>
    {%endif%}
</div>
{%for answer in question|get_answer_set%}
<div>
    <div class="voting-answer float-left" style='padding-right: 10px'>
        {%if user|has_upvotedans:answer%}
        <div class="button" ><a style = "color:  #f48024;" class= "btn btn-light"href = "{%url 'doubts:vote-answer' answer.id 1%}"><i class="fa fa-arrow-up" ></i></a></div>
        {%else%}
        <div class="button" ><a style = "color:  #131010;" class= "btn btn-light"href = "{%url 'doubts:vote-answer' answer.id 1%}"><i class="fa fa-arrow-up" ></i></a></div>
        {%endif%}
        <div class="votes" style="padding-left: 15px;">{{answer.upvotes}}</div>
        {%if user|has_downvotedans:answer%}
        <div class="button"><a style = "color:  #f48024;"  class= "btn btn-light"href= "{%url 'doubts:vote-answer' answer.id 0%}"><i class="fa fa-arrow-down"></i></a></div>
        {%else%}
        <div class="button"><a style = "color:  #131010;" class= "btn btn-light"href= "{%url 'doubts:vote-answer' answer.id 0%}"><i class="fa fa-arrow-down"></i></a></div>
        {%endif%}
    </div>
    <div id='answer-box'>
        <div id="answer-text">{{answer.text|linebreaks|urlizetrunc:50}}</div>
        {%if answer.author == user%}
        <div id='answer-other-details' style="padding-top: 15px;" class='float-right'>
            <small class="text-muted" style="text-align: center;">Your Answer</a></small></br>
            <small class="text-muted float-right"><a class=" btn btn-outline-secondary btn-sm" href="{%url 'doubts:edit-answer' question.pk answer.pk%}">Edit</a>
                <a class=" btn btn-outline-secondary btn-sm" href="{%url 'doubts:delete-answer' question.pk answer.pk%}">Delete</a>
            </small>
        </div>
        {%else%}
            <div id='answer-other-details' style="padding-top: 15px;" class='float-right'>
                <small class="text-muted">Answered By: <a href="{%url 'doubts:user-index' answer.author.id %}" class="profile-link">{{answer.author}}</a></small></br>
                <small class="text-muted">{{answer.date_answered}}</small>
            </div>
        {%endif%}
    </div>
</div>
{%endfor%}
</div>
</div>
{%endblock content%}

doubts/templates/doubts/index.html
{% extends "doubts/base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'doubts/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <div class="card poll-card" style="margin-bottom: 10px;">
        <div class="card-header" style="padding-bottom: 8px;padding-top: 8px;">
            <div class="article-metadata">
                <span class="badge badge-pill badge-dark">{{question.get_subject_display}}</span> <small class="mr-2 text-muted" style="
                margin-left: 5px;
            ">| Posted By <a href="{%url 'doubts:user-index' question.asker.id %}" class="profile-link">{{ question.asker }}</a></small>
          </div>
        </div>
        <div class="card-body" style="padding-bottom: 5px;padding-top: 15px;">
            <h5><a class="question-link" href="{%url 'doubts:details' question.id%}">{{ question }}</a></h5>
        </div>
    </div>
    {% endfor %}
    </ul>
    {%ifnotequal page_obj.paginator.num_pages 1%}
    <div class="btn-group float-right" role="group" aria-label="Basic example">
        {%if page_obj.has_previous%}
            <a class="btn btn-light" href="?page=1"><i class="fas fa-angle-double-left"></i></a>
            <a class="btn btn-light" href="?page={{page_obj.previous_page_number}}"><i class="fas fa-angle-left"></i></a>
        {%endif%}
        {%for num in page_obj.paginator.page_range%}
            {%if num == page_obj.number%}
                <button type="button" class="btn btn-secondary">{{ num }}</button>
            {%elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
                <a class="btn btn-light" href="?page={{num}}">{{ num }}</a>
            {%endif%}
        {%endfor%}
        {%if page_obj.has_next%}
            <a class="btn btn-light" href='?page={{page_obj.next_page_number}}'><i class="fas fa-angle-right"></i></a>
            <a class="btn btn-light" href="?page={{page_obj.paginator.num_pages}}"><i class="fas fa-angle-double-right"></i></a>
        {%endif%}
      </div>
    {%endifnotequal%}
{% else %}
    <h3 class='text-center'>No questions. Much Wow.</h3>
{% endif %}
{% endblock content%}

doubts/templates/doubts/question_form.html
{%extends "doubts/base.html"%}
{%load static%}
{% load crispy_forms_tags%}
{%block content%}
<div class="content-section pd-8 ">
    <form method="POST">
        {%csrf_token%}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                Post Question
            </legend>
            {{form|crispy}}
        </fieldset>
        <div class="form-group"><button class="btn btn-outline-info" type="submit">Publish</button></div>
    </form>
</div>

{%endblock content %}

doubts/templates/doubts/user_index.html
{% extends "doubts/base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'doubts/style.css' %}">
<div class="text-center">
    <h1><code>{{object.username}}</code></h1></br>
    <h5 class="font-weight-light"><code>Email: {{object.email}}</code></h5></br>

    <h5 class="font-weight-light"><code>Questions Asked: {{object.profile.questions_asked}}</code></h5></br>
    <h5 class="font-weight-light"><code>Answers Published: {{object.profile.questions_answered}}</code></h5></br>
    <h5 class="font-weight-light"><code>Karma Points: {{object.profile.karma_points}}</code></h5></br>
</div>
{% endblock content%}